// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_signin.proto

package com.mogujie.tt.protobuf;

public final class InterfaceSignin {
  private InterfaceSignin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface pbui_Item_MeetSignInDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_MeetSignInDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *人员ID
     * </pre>
     *
     * <code>fixed32 nameId = 1;</code>
     */
    int getNameId();

    /**
     * <pre>
     *日期 时间 单位:秒
     * </pre>
     *
     * <code>fixed64 utcseconds = 2;</code>
     */
    long getUtcseconds();

    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 3;</code>
     */
    int getSigninType();

    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 4;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 5;</code>
     */
    com.google.protobuf.ByteString getPsigndata();
  }
  /**
   * <pre>
   *会议签到
   * </pre>
   *
   * Protobuf type {@code pbui_Item_MeetSignInDetailInfo}
   */
  public  static final class pbui_Item_MeetSignInDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_MeetSignInDetailInfo, pbui_Item_MeetSignInDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_MeetSignInDetailInfo)
      pbui_Item_MeetSignInDetailInfoOrBuilder {
    private pbui_Item_MeetSignInDetailInfo() {
      password_ = com.google.protobuf.ByteString.EMPTY;
      psigndata_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int NAMEID_FIELD_NUMBER = 1;
    private int nameId_;
    /**
     * <pre>
     *人员ID
     * </pre>
     *
     * <code>fixed32 nameId = 1;</code>
     */
    public int getNameId() {
      return nameId_;
    }
    /**
     * <pre>
     *人员ID
     * </pre>
     *
     * <code>fixed32 nameId = 1;</code>
     */
    private void setNameId(int value) {
      
      nameId_ = value;
    }
    /**
     * <pre>
     *人员ID
     * </pre>
     *
     * <code>fixed32 nameId = 1;</code>
     */
    private void clearNameId() {
      
      nameId_ = 0;
    }

    public static final int UTCSECONDS_FIELD_NUMBER = 2;
    private long utcseconds_;
    /**
     * <pre>
     *日期 时间 单位:秒
     * </pre>
     *
     * <code>fixed64 utcseconds = 2;</code>
     */
    public long getUtcseconds() {
      return utcseconds_;
    }
    /**
     * <pre>
     *日期 时间 单位:秒
     * </pre>
     *
     * <code>fixed64 utcseconds = 2;</code>
     */
    private void setUtcseconds(long value) {
      
      utcseconds_ = value;
    }
    /**
     * <pre>
     *日期 时间 单位:秒
     * </pre>
     *
     * <code>fixed64 utcseconds = 2;</code>
     */
    private void clearUtcseconds() {
      
      utcseconds_ = 0L;
    }

    public static final int SIGNIN_TYPE_FIELD_NUMBER = 3;
    private int signinType_;
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 3;</code>
     */
    public int getSigninType() {
      return signinType_;
    }
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 3;</code>
     */
    private void setSigninType(int value) {
      
      signinType_ = value;
    }
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 3;</code>
     */
    private void clearSigninType() {
      
      signinType_ = 0;
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString password_;
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 4;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 4;</code>
     */
    private void setPassword(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
    }
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 4;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }

    public static final int PSIGNDATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString psigndata_;
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 5;</code>
     */
    public com.google.protobuf.ByteString getPsigndata() {
      return psigndata_;
    }
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 5;</code>
     */
    private void setPsigndata(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      psigndata_ = value;
    }
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 5;</code>
     */
    private void clearPsigndata() {
      
      psigndata_ = getDefaultInstance().getPsigndata();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nameId_ != 0) {
        output.writeFixed32(1, nameId_);
      }
      if (utcseconds_ != 0L) {
        output.writeFixed64(2, utcseconds_);
      }
      if (signinType_ != 0) {
        output.writeFixed32(3, signinType_);
      }
      if (!password_.isEmpty()) {
        output.writeBytes(4, password_);
      }
      if (!psigndata_.isEmpty()) {
        output.writeBytes(5, psigndata_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (nameId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, nameId_);
      }
      if (utcseconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, utcseconds_);
      }
      if (signinType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, signinType_);
      }
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, password_);
      }
      if (!psigndata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, psigndata_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议签到
     * </pre>
     *
     * Protobuf type {@code pbui_Item_MeetSignInDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_MeetSignInDetailInfo)
        com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *人员ID
       * </pre>
       *
       * <code>fixed32 nameId = 1;</code>
       */
      public int getNameId() {
        return instance.getNameId();
      }
      /**
       * <pre>
       *人员ID
       * </pre>
       *
       * <code>fixed32 nameId = 1;</code>
       */
      public Builder setNameId(int value) {
        copyOnWrite();
        instance.setNameId(value);
        return this;
      }
      /**
       * <pre>
       *人员ID
       * </pre>
       *
       * <code>fixed32 nameId = 1;</code>
       */
      public Builder clearNameId() {
        copyOnWrite();
        instance.clearNameId();
        return this;
      }

      /**
       * <pre>
       *日期 时间 单位:秒
       * </pre>
       *
       * <code>fixed64 utcseconds = 2;</code>
       */
      public long getUtcseconds() {
        return instance.getUtcseconds();
      }
      /**
       * <pre>
       *日期 时间 单位:秒
       * </pre>
       *
       * <code>fixed64 utcseconds = 2;</code>
       */
      public Builder setUtcseconds(long value) {
        copyOnWrite();
        instance.setUtcseconds(value);
        return this;
      }
      /**
       * <pre>
       *日期 时间 单位:秒
       * </pre>
       *
       * <code>fixed64 utcseconds = 2;</code>
       */
      public Builder clearUtcseconds() {
        copyOnWrite();
        instance.clearUtcseconds();
        return this;
      }

      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 3;</code>
       */
      public int getSigninType() {
        return instance.getSigninType();
      }
      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 3;</code>
       */
      public Builder setSigninType(int value) {
        copyOnWrite();
        instance.setSigninType(value);
        return this;
      }
      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 3;</code>
       */
      public Builder clearSigninType() {
        copyOnWrite();
        instance.clearSigninType();
        return this;
      }

      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 4;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return instance.getPassword();
      }
      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 4;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 4;</code>
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }

      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 5;</code>
       */
      public com.google.protobuf.ByteString getPsigndata() {
        return instance.getPsigndata();
      }
      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 5;</code>
       */
      public Builder setPsigndata(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPsigndata(value);
        return this;
      }
      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 5;</code>
       */
      public Builder clearPsigndata() {
        copyOnWrite();
        instance.clearPsigndata();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_MeetSignInDetailInfo)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo other = (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo) arg1;
          nameId_ = visitor.visitInt(nameId_ != 0, nameId_,
              other.nameId_ != 0, other.nameId_);
          utcseconds_ = visitor.visitLong(utcseconds_ != 0L, utcseconds_,
              other.utcseconds_ != 0L, other.utcseconds_);
          signinType_ = visitor.visitInt(signinType_ != 0, signinType_,
              other.signinType_ != 0, other.signinType_);
          password_ = visitor.visitByteString(password_ != com.google.protobuf.ByteString.EMPTY, password_,
              other.password_ != com.google.protobuf.ByteString.EMPTY, other.password_);
          psigndata_ = visitor.visitByteString(psigndata_ != com.google.protobuf.ByteString.EMPTY, psigndata_,
              other.psigndata_ != com.google.protobuf.ByteString.EMPTY, other.psigndata_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  nameId_ = input.readFixed32();
                  break;
                }
                case 17: {

                  utcseconds_ = input.readFixed64();
                  break;
                }
                case 29: {

                  signinType_ = input.readFixed32();
                  break;
                }
                case 34: {

                  password_ = input.readBytes();
                  break;
                }
                case 42: {

                  psigndata_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_MeetSignInDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_MeetSignInDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_MeetSignInDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_MeetSignInDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_MeetSignInDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_MeetSignInDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> 
        getItemList();
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo getItem(int index);
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    int getItemCount();
  }
  /**
   * <pre>
   *type:Pb_TYPE_MEET_INTERFACE_MEETSIGN
   *method: query
   * </pre>
   *
   * Protobuf type {@code pbui_Type_MeetSignInDetailInfo}
   */
  public  static final class pbui_Type_MeetSignInDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_MeetSignInDetailInfo, pbui_Type_MeetSignInDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_MeetSignInDetailInfo)
      pbui_Type_MeetSignInDetailInfoOrBuilder {
    private pbui_Type_MeetSignInDetailInfo() {
      item_ = emptyProtobufList();
    }
    public static final int ITEM_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> item_;
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void addItem(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void addItem(
        com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *type:Pb_TYPE_MEET_INTERFACE_MEETSIGN
     *method: query
     * </pre>
     *
     * Protobuf type {@code pbui_Type_MeetSignInDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_MeetSignInDetailInfo)
        com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder addItem(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder addItem(
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <code>repeated .pbui_Item_MeetSignInDetailInfo item = 1;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_MeetSignInDetailInfo)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo other = (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo) arg1;
          item_= visitor.visitList(item_, other.item_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Item_MeetSignInDetailInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_MeetSignInDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_MeetSignInDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_MeetSignInDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_MeetSignInDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_MeetSignInDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_DoMeetSignInoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DoMeetSignIno)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *指定签到的人员ID,为0表示当前绑定的人员
     * </pre>
     *
     * <code>fixed32 memberid = 1;</code>
     */
    int getMemberid();

    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 2;</code>
     */
    int getSigninType();

    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 3;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 4;</code>
     */
    com.google.protobuf.ByteString getPsigndata();
  }
  /**
   * <pre>
   *发送会议签到
   *type:Pb_TYPE_MEET_INTERFACE_MEETSIGN
   *method: add
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DoMeetSignIno}
   */
  public  static final class pbui_Type_DoMeetSignIno extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DoMeetSignIno, pbui_Type_DoMeetSignIno.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DoMeetSignIno)
      pbui_Type_DoMeetSignInoOrBuilder {
    private pbui_Type_DoMeetSignIno() {
      password_ = com.google.protobuf.ByteString.EMPTY;
      psigndata_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private int memberid_;
    /**
     * <pre>
     *指定签到的人员ID,为0表示当前绑定的人员
     * </pre>
     *
     * <code>fixed32 memberid = 1;</code>
     */
    public int getMemberid() {
      return memberid_;
    }
    /**
     * <pre>
     *指定签到的人员ID,为0表示当前绑定的人员
     * </pre>
     *
     * <code>fixed32 memberid = 1;</code>
     */
    private void setMemberid(int value) {
      
      memberid_ = value;
    }
    /**
     * <pre>
     *指定签到的人员ID,为0表示当前绑定的人员
     * </pre>
     *
     * <code>fixed32 memberid = 1;</code>
     */
    private void clearMemberid() {
      
      memberid_ = 0;
    }

    public static final int SIGNIN_TYPE_FIELD_NUMBER = 2;
    private int signinType_;
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 2;</code>
     */
    public int getSigninType() {
      return signinType_;
    }
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 2;</code>
     */
    private void setSigninType(int value) {
      
      signinType_ = value;
    }
    /**
     * <pre>
     *签到方式 参见Pb_MeetSignType
     * </pre>
     *
     * <code>fixed32 signin_type = 2;</code>
     */
    private void clearSigninType() {
      
      signinType_ = 0;
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString password_;
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 3;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 3;</code>
     */
    private void setPassword(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
    }
    /**
     * <pre>
     *签到密码
     * </pre>
     *
     * <code>bytes password = 3;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }

    public static final int PSIGNDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString psigndata_;
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 4;</code>
     */
    public com.google.protobuf.ByteString getPsigndata() {
      return psigndata_;
    }
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 4;</code>
     */
    private void setPsigndata(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      psigndata_ = value;
    }
    /**
     * <pre>
     *如果有图片签到则为png图片数据(二进制转hex编码)
     * </pre>
     *
     * <code>bytes psigndata = 4;</code>
     */
    private void clearPsigndata() {
      
      psigndata_ = getDefaultInstance().getPsigndata();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (memberid_ != 0) {
        output.writeFixed32(1, memberid_);
      }
      if (signinType_ != 0) {
        output.writeFixed32(2, signinType_);
      }
      if (!password_.isEmpty()) {
        output.writeBytes(3, password_);
      }
      if (!psigndata_.isEmpty()) {
        output.writeBytes(4, psigndata_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (memberid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, memberid_);
      }
      if (signinType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, signinType_);
      }
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, password_);
      }
      if (!psigndata_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, psigndata_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *发送会议签到
     *type:Pb_TYPE_MEET_INTERFACE_MEETSIGN
     *method: add
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DoMeetSignIno}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DoMeetSignIno)
        com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignInoOrBuilder {
      // Construct using com.mogujie.tt.com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *指定签到的人员ID,为0表示当前绑定的人员
       * </pre>
       *
       * <code>fixed32 memberid = 1;</code>
       */
      public int getMemberid() {
        return instance.getMemberid();
      }
      /**
       * <pre>
       *指定签到的人员ID,为0表示当前绑定的人员
       * </pre>
       *
       * <code>fixed32 memberid = 1;</code>
       */
      public Builder setMemberid(int value) {
        copyOnWrite();
        instance.setMemberid(value);
        return this;
      }
      /**
       * <pre>
       *指定签到的人员ID,为0表示当前绑定的人员
       * </pre>
       *
       * <code>fixed32 memberid = 1;</code>
       */
      public Builder clearMemberid() {
        copyOnWrite();
        instance.clearMemberid();
        return this;
      }

      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 2;</code>
       */
      public int getSigninType() {
        return instance.getSigninType();
      }
      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 2;</code>
       */
      public Builder setSigninType(int value) {
        copyOnWrite();
        instance.setSigninType(value);
        return this;
      }
      /**
       * <pre>
       *签到方式 参见Pb_MeetSignType
       * </pre>
       *
       * <code>fixed32 signin_type = 2;</code>
       */
      public Builder clearSigninType() {
        copyOnWrite();
        instance.clearSigninType();
        return this;
      }

      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 3;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return instance.getPassword();
      }
      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 3;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <pre>
       *签到密码
       * </pre>
       *
       * <code>bytes password = 3;</code>
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }

      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 4;</code>
       */
      public com.google.protobuf.ByteString getPsigndata() {
        return instance.getPsigndata();
      }
      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 4;</code>
       */
      public Builder setPsigndata(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPsigndata(value);
        return this;
      }
      /**
       * <pre>
       *如果有图片签到则为png图片数据(二进制转hex编码)
       * </pre>
       *
       * <code>bytes psigndata = 4;</code>
       */
      public Builder clearPsigndata() {
        copyOnWrite();
        instance.clearPsigndata();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DoMeetSignIno)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno other = (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno) arg1;
          memberid_ = visitor.visitInt(memberid_ != 0, memberid_,
              other.memberid_ != 0, other.memberid_);
          signinType_ = visitor.visitInt(signinType_ != 0, signinType_,
              other.signinType_ != 0, other.signinType_);
          password_ = visitor.visitByteString(password_ != com.google.protobuf.ByteString.EMPTY, password_,
              other.password_ != com.google.protobuf.ByteString.EMPTY, other.password_);
          psigndata_ = visitor.visitByteString(psigndata_ != com.google.protobuf.ByteString.EMPTY, psigndata_,
              other.psigndata_ != com.google.protobuf.ByteString.EMPTY, other.psigndata_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  memberid_ = input.readFixed32();
                  break;
                }
                case 21: {

                  signinType_ = input.readFixed32();
                  break;
                }
                case 26: {

                  password_ = input.readBytes();
                  break;
                }
                case 34: {

                  psigndata_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DoMeetSignIno)
    private static final com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DoMeetSignIno();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoMeetSignIno getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DoMeetSignIno> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DoMeetSignIno> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_Type_DoDeleteMeetSignInoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Type_DoDeleteMeetSignIno)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *指定会议ID 0表示绑定的会议
     * </pre>
     *
     * <code>fixed32 meetingid = 1;</code>
     */
    int getMeetingid();

    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    java.util.List<java.lang.Integer> getMemberidsList();
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    int getMemberidsCount();
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    int getMemberids(int index);
  }
  /**
   * <pre>
   *删除会议签到
   *type:Pb_TYPE_MEET_INTERFACE_MEETVOTESIGNED
   *method: del
   * </pre>
   *
   * Protobuf type {@code pbui_Type_DoDeleteMeetSignIno}
   */
  public  static final class pbui_Type_DoDeleteMeetSignIno extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Type_DoDeleteMeetSignIno, pbui_Type_DoDeleteMeetSignIno.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Type_DoDeleteMeetSignIno)
      pbui_Type_DoDeleteMeetSignInoOrBuilder {
    private pbui_Type_DoDeleteMeetSignIno() {
      memberids_ = emptyIntList();
    }
    private int bitField0_;
    public static final int MEETINGID_FIELD_NUMBER = 1;
    private int meetingid_;
    /**
     * <pre>
     *指定会议ID 0表示绑定的会议
     * </pre>
     *
     * <code>fixed32 meetingid = 1;</code>
     */
    public int getMeetingid() {
      return meetingid_;
    }
    /**
     * <pre>
     *指定会议ID 0表示绑定的会议
     * </pre>
     *
     * <code>fixed32 meetingid = 1;</code>
     */
    private void setMeetingid(int value) {
      
      meetingid_ = value;
    }
    /**
     * <pre>
     *指定会议ID 0表示绑定的会议
     * </pre>
     *
     * <code>fixed32 meetingid = 1;</code>
     */
    private void clearMeetingid() {
      
      meetingid_ = 0;
    }

    public static final int MEMBERIDS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList memberids_;
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getMemberidsList() {
      return memberids_;
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    public int getMemberidsCount() {
      return memberids_.size();
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    public int getMemberids(int index) {
      return memberids_.getInt(index);
    }
    private void ensureMemberidsIsMutable() {
      if (!memberids_.isModifiable()) {
        memberids_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(memberids_);
       }
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    private void setMemberids(
        int index, int value) {
      ensureMemberidsIsMutable();
      memberids_.setInt(index, value);
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    private void addMemberids(int value) {
      ensureMemberidsIsMutable();
      memberids_.addInt(value);
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    private void addAllMemberids(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureMemberidsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, memberids_);
    }
    /**
     * <pre>
     *为空表示删除指定会议的全部人员签到
     * </pre>
     *
     * <code>repeated fixed32 memberids = 2;</code>
     */
    private void clearMemberids() {
      memberids_ = emptyIntList();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (meetingid_ != 0) {
        output.writeFixed32(1, meetingid_);
      }
      for (int i = 0; i < memberids_.size(); i++) {
        output.writeFixed32(2, memberids_.getInt(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (meetingid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, meetingid_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getMemberidsList().size();
        size += dataSize;
        size += 1 * getMemberidsList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *删除会议签到
     *type:Pb_TYPE_MEET_INTERFACE_MEETVOTESIGNED
     *method: del
     * </pre>
     *
     * Protobuf type {@code pbui_Type_DoDeleteMeetSignIno}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Type_DoDeleteMeetSignIno)
        com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignInoOrBuilder {
      // Construct using com.mogujie.tt.com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *指定会议ID 0表示绑定的会议
       * </pre>
       *
       * <code>fixed32 meetingid = 1;</code>
       */
      public int getMeetingid() {
        return instance.getMeetingid();
      }
      /**
       * <pre>
       *指定会议ID 0表示绑定的会议
       * </pre>
       *
       * <code>fixed32 meetingid = 1;</code>
       */
      public Builder setMeetingid(int value) {
        copyOnWrite();
        instance.setMeetingid(value);
        return this;
      }
      /**
       * <pre>
       *指定会议ID 0表示绑定的会议
       * </pre>
       *
       * <code>fixed32 meetingid = 1;</code>
       */
      public Builder clearMeetingid() {
        copyOnWrite();
        instance.clearMeetingid();
        return this;
      }

      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getMemberidsList() {
        return java.util.Collections.unmodifiableList(
            instance.getMemberidsList());
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public int getMemberidsCount() {
        return instance.getMemberidsCount();
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public int getMemberids(int index) {
        return instance.getMemberids(index);
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public Builder setMemberids(
          int index, int value) {
        copyOnWrite();
        instance.setMemberids(index, value);
        return this;
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public Builder addMemberids(int value) {
        copyOnWrite();
        instance.addMemberids(value);
        return this;
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public Builder addAllMemberids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        copyOnWrite();
        instance.addAllMemberids(values);
        return this;
      }
      /**
       * <pre>
       *为空表示删除指定会议的全部人员签到
       * </pre>
       *
       * <code>repeated fixed32 memberids = 2;</code>
       */
      public Builder clearMemberids() {
        copyOnWrite();
        instance.clearMemberids();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Type_DoDeleteMeetSignIno)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          memberids_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno other = (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno) arg1;
          meetingid_ = visitor.visitInt(meetingid_ != 0, meetingid_,
              other.meetingid_ != 0, other.meetingid_);
          memberids_= visitor.visitIntList(memberids_, other.memberids_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  meetingid_ = input.readFixed32();
                  break;
                }
                case 21: {
                  if (!memberids_.isModifiable()) {
                    memberids_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(memberids_);
                  }
                  memberids_.addInt(input.readFixed32());
                  break;
                }
                case 18: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  if (!memberids_.isModifiable() && input.getBytesUntilLimit() > 0) {
                    final int currentSize = memberids_.size();
                    memberids_ = memberids_.mutableCopyWithCapacity(
                        currentSize + (length/4));
                  }
                  while (input.getBytesUntilLimit() > 0) {
                    memberids_.addInt(input.readFixed32());
                  }
                  input.popLimit(limit);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Type_DoDeleteMeetSignIno)
    private static final com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Type_DoDeleteMeetSignIno();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceSignin.pbui_Type_DoDeleteMeetSignIno getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Type_DoDeleteMeetSignIno> PARSER;

    public static com.google.protobuf.Parser<pbui_Type_DoDeleteMeetSignIno> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
